apiVersion: batch/v1
kind: Job
metadata:
  name: k6-job
spec:
  # 🟢 ADD THIS: 1 pod = Standard Load. 10 pods = Massive Distributed Load.
  parallelism: 2
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: k6-container
        image: k6-image:latest
        imagePullPolicy: Never
        # 🟢 FIX: Use 'sh -c' to run K6, then print a flag, then sleep!
        command: ["/bin/sh", "-c"]
        args: ["k6 run /app/tests/performance/register_load_test.js; echo '---K6_FINISHED---'; sleep 60"]
      restartPolicy: Never
